"""create table books

Revision ID: 81878bed3e8d
Revises: 
Create Date: 2021-06-12 14:48:01.082516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81878bed3e8d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("isbn", sa.String(length=30), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("_id"),
    )
    op.create_index(op.f("ix_book_isbn"), "book", ["isbn"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_isbn"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
